using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BepInEx.Logging;
using HarmonyLib;
using MonsterTrain2Poju.Model;
using Newtonsoft.Json.Linq;

namespace MonsterTrain2Poju.Probe
{
    internal static class HandRemovalScenario
    {
        internal static readonly List<Record> Records = new List<Record>();
        private static BattlePlayRules? rules;
        internal static void Prepare(AllGameManagers managers, ManualLogSource log, bool lethal)
        {
            SaveManager save = managers.GetSaveManager(); CardManager cards = managers.GetCardManager()!;
            CardState[] owned = cards.GetAllCards(new List<CardState>()).ToArray();
            CardState[] spells = owned.Where(card => card.GetCardType() == CardType.Spell &&
                card.GetEffects().Any(effect => effect.GetEffectStateName() == "CardEffectFloorRearrange")).ToArray();
            CardData data = save.GetAllGameData().FindCardData(spells[0].GetCardDataID())!;
            var effects = data.GetEffects(); effects.Clear();
            effects.Add(Effect("CardEffectDamage", 0, TargetMode.Tower, Team.Type.Heroes));
            var upgrade = Effect("CardEffectAddTempCardUpgradeToCardsInHand", 0, TargetMode.Hand);
            CardUpgradeData upgradeData = DynamicUpgradeScenario.Upgrade("PojuRemovalTemporary", "0289f8a5-63ef-42e7-927b-238190000001", 2, 0, 0, 2, "armor", 0);
            Set(upgrade, "paramCardUpgradeData", upgradeData); effects.Add(upgrade);
            effects.Add(Effect("CardEffectDraw", 2));
            if (lethal)
            {
                effects.Add(Effect("CardEffectDamage", 10, TargetMode.Tower, Team.Type.Monsters));
                effects.Add(Effect("CardEffectDiscardHand", 1)); // Consume immediately after friendly deaths.
            }
            effects.Add(Effect("CardEffectDiscardHand", 0));
            effects.Add(Effect("CardEffectDraw", 3));
            effects.Add(Effect("CardEffectDiscardHand", 1));
            effects.Add(Effect("CardEffectDiscardHand", 1)); // Empty hand: reset this effect's latent counter to zero.
            effects.Add(Effect("CardEffectDraw", 2));
            effects.Add(Effect("CardEffectDiscardHand", 0));
            effects.Add(Effect("CardEffectDraw", 1));
            effects.Add(Effect("CardEffectDiscardHand", 1));
            effects.Add(Effect("CardEffectDraw", 1));
            var ignored = Effect("CardEffectDiscardHand", 2); // Native unknown enum is a no-op, not a range consumer.
            Set(ignored, "useIntRange", true); Set(ignored, "paramMinInt", -100); Set(ignored, "paramMaxInt", 100); effects.Add(ignored);
            effects.Add(Effect("CardEffectBuffDamage", 4, TargetMode.Tower, Team.Type.Monsters));
            Set(data, "targetless", false); Set(data, "targetsRoom", true);
            foreach (CardState card in spells) card.Setup(data, save);
            foreach (CardState card in owned)
            {
                var temporary = new CardUpgradeState(); temporary.Setup(); temporary.SetAttackDamage(1);
                temporary.SetAdditionalHP(2); temporary.SetRemoveOnDiscard(true); card.ApplyTemporaryUpgrade(temporary, save);
            }
            if (!cards.GetHand().Contains(spells[0])) cards.DrawSpecificCard(spells[0]);
            managers.GetPlayerManager().AddEnergy(1);
            Set(managers.GetCombatManager()!, "combatStateChanged", true);
            rules = null; // Capture the complete root rules, including cards generated by future waves.
            log.LogInfo("HAND-REMOVAL-PREPARED forward discards, repeated consumes, double exhaustion statistics, live reshuffles, discard-only upgrade removal, latent effect counters, ignored ranges and transient standby slots; lethal=" + lethal);
        }
        private static CardEffectData Effect(string type, int amount, TargetMode mode = TargetMode.Room, Team.Type team = Team.Type.None)
        { var effect = new CardEffectData(type, null!, team); effect.Cheat_SetTargetMode(mode); Set(effect, "paramInt", amount); return effect; }
        private static void Set(object target, string field, object value) => AccessTools.Field(target.GetType(), field).SetValue(target, value);

        internal sealed class Snapshot
        {
            public CombatContext Context { get; set; } = null!;
            public CardPileState[] OtherPiles { get; set; } = Array.Empty<CardPileState>();
            public int[] PendingExhaustedCards { get; set; } = Array.Empty<int>();
            public bool ExhaustionRunsTriggerQueue { get; set; }
        }
        internal sealed class Record
        {
            public int CardId { get; set; }
            public int EffectIndex { get; set; }
            public int Mode { get; set; }
            public Snapshot Before { get; set; } = null!;
            public HandRemovalResult Predicted { get; set; } = null!;
            public Snapshot? Actual { get; set; }
            public int ConsumedCount { get; set; }
            public string? Difference { get; set; }
        }
        private static Snapshot Capture()
        {
            FullBattleTrace trace = FullBattleTrace.Active!;
            AllGameManagers managers = AllGameManagers.Instance!;
            var standby = (Dictionary<CardState, RemoveFromStandByCondition>)AccessTools.Field(typeof(CardManager), "pileStandBy").GetValue(managers.GetCardManager()!);
            var units = new List<CharacterState>();
            RoomManager rooms = managers.GetRoomManager()!;
            rooms.GetRoom(rooms.GetSelectedRoom()).AddCharactersToList(units, Team.Type.Heroes | Team.Type.Monsters);
            return new Snapshot { Context = trace.CaptureContext(), OtherPiles = trace.CaptureOtherPiles(),
                PendingExhaustedCards = standby.Where(pair => pair.Value?.GetReturnLocation() == CardPile.ExhaustedPile)
                    .Select(pair => trace.CardId(pair.Key)).ToArray(), ExhaustionRunsTriggerQueue = units.Count > 0 };
        }
        private static JToken Comparable(CombatContext context, IReadOnlyList<CardPileState>? piles) => JToken.FromObject(new
        { Context = context, OtherPiles = piles });
        private static IEnumerator Wrap(IEnumerator native, CardEffectState effect, CardEffectParams parameters)
        {
            Record? record = null;
            try
            {
                if (parameters.playedCard != null && FullBattleTrace.Active != null && !AllGameManagers.Instance!.GetSaveManager().PreviewMode)
                {
                    rules ??= FullBattleTrace.Active.CaptureDecision().PlayRules ?? throw new InvalidOperationException("Missing root card rules.");
                    Snapshot before = Capture(); int id = FullBattleTrace.Active.CardId(parameters.playedCard);
                    int index = parameters.playedCard.GetEffectStates().IndexOf(effect);
                    record = new Record { CardId = id, EffectIndex = index, Mode = effect.GetParamInt(), Before = before,
                        Predicted = HandRemovalModel.Apply(before.Context, effect.GetParamInt(), id, index, rules, before.OtherPiles,
                            before.PendingExhaustedCards, before.ExhaustionRunsTriggerQueue) };
                    Records.Add(record);
                }
            }
            catch (Exception error) { FullBattleTrace.Active?.CaptureFailure(error); }
            while (native.MoveNext()) yield return native.Current;
            if (record == null) yield break;
            try
            {
                record.Actual = Capture(); record.ConsumedCount = ((CardEffectDiscardHand)effect.GetCardEffect()).GetNumCardsConsumed();
                record.Difference = !record.Predicted.Supported ? record.Predicted.UnsupportedReason :
                    record.Predicted.ConsumedCount != record.ConsumedCount || !JToken.DeepEquals(
                        Comparable(record.Predicted.Context!, record.Predicted.OtherPiles), Comparable(record.Actual.Context, record.Actual.OtherPiles))
                        ? "Hand removal context, statistics, counter or pile allocation differs" : null;
                UnityEngine.Debug.Log("HAND-REMOVAL-" + (record.Difference == null ? "MATCH" : "MISMATCH") + " effect=" + record.EffectIndex + " mode=" + record.Mode);
            }
            catch (Exception error) { FullBattleTrace.Active?.CaptureFailure(error); }
        }
        [HarmonyPatch(typeof(CardEffectDiscardHand), nameof(CardEffectDiscardHand.ApplyEffect))]
        private static class RemovalPatch
        {
            private static void Postfix(CardEffectState cardEffectState, CardEffectParams cardEffectParams, ref IEnumerator __result)
            {
                if (Environment.GetEnvironmentVariable("MT2_PROBE_MODIFIERS") is "hand-removal" or "hand-removal-lethal")
                    __result = Wrap(__result, cardEffectState, cardEffectParams);
            }
        }
    }
}
