#requires -Version 7.4
$ErrorActionPreference = 'Stop'
$workspace = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$fixtures = @('full-battle-steward-once.json', 'full-battle-no-cards.json', 'full-battle-units-and-junk.json',
    'full-battle-units-spells-and-junk.json', 'full-battle-statistics.json.gz', 'full-battle-numeric-upgrades.json.gz',
    'full-battle-dynamic-upgrades.json.gz', 'full-battle-sacrifice-upgrades.json.gz',
    'full-battle-hand-upgrades.json.gz', 'full-battle-targeted-hand-upgrades.json.gz',
    'full-battle-healing.json.gz', 'full-battle-healing-triggers.json.gz', 'full-battle-room-spells.json.gz',
    'full-battle-terminal-spells.json.gz',
    'full-battle-post-kill-spells.json.gz',
    'full-battle-random-spells.json.gz',
    'full-battle-random-status.json.gz',
    'full-battle-cross-room-spells.json.gz', 'full-battle-cross-room-targets.json.gz',
    'full-battle-attack-buffs.json.gz',
    'full-battle-max-health-spells.json.gz', 'full-battle-max-health-lethal.json.gz',
    'full-battle-numeric-ranges-ui-isolated.json.gz', 'full-battle-numeric-ranges-lethal-ui-isolated.json.gz',
    'full-battle-target-filters.json.gz',
    'full-battle-drawing-ui-isolated.json.gz',
    'full-battle-hand-removal.json.gz', 'full-battle-hand-removal-lethal.json.gz',
    'full-battle-generation.json.gz', 'full-battle-generation-lethal.json.gz',
    'full-battle-shared-piles.json.gz', 'full-battle-shared-piles-lethal.json.gz',
    'full-battle-damage-scaling.json.gz',
    'full-battle-dynamic-statistics.json.gz',
    'full-battle-status-scaling.json.gz',
    'full-battle-unit-upgrade-scaling.json.gz',
    'full-battle-unit-trigger-upgrades.json.gz',
    'full-battle-spawn-triggers.json.gz', 'full-battle-spawn-triggers-lethal.json.gz',
    'full-battle-unit-turn-begin.json.gz',
    'full-battle-team-turn-begin.json.gz',
    'full-battle-pre-hand-discard.json.gz', 'full-battle-pre-hand-discard-lethal.json.gz',
    'full-battle-clone-upgrade-refresh.json.gz',
    'full-battle-pre-combat.json.gz',
    'full-battle-statistic-cache.json.gz',
    'full-battle-triggered-healing.json.gz',
    'full-battle-post-combat-healing.json.gz',
    'full-battle-triggered-damage.json.gz',
    'full-battle-damage-death-queue.json.gz',
    'full-battle-terminal-death-damage.json.gz',
    'card-modifier-calibration.json.gz', 'rng-calibration.json', 'gold-reward-calibration.json.gz',
    'standby-routing-calibration.json.gz', 'ui-rng-isolation-calibration.json.gz',
    'statistic-query-calibration.json.gz', 'statistic-overflow-calibration.json.gz',
    'statistic-zero-increment-calibration.json.gz') |
    ForEach-Object { Join-Path $workspace ('tests\fixtures\' + $_) }
dotnet run --project (Join-Path $workspace 'src\ModelChecks\ModelChecks.csproj') -c Release -- @fixtures
if ($LASTEXITCODE -ne 0) { throw 'Independent model checks failed.' }
